# Generated by Django 6.0.4 on 2026-06-18 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chat', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('message', 'Message'), ('verification', 'Verification'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('message', models.TextField(help_text='Human-readable notification body shown in the UI.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Set when this notification relates to a booking event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('conversation', models.ForeignKey(blank=True, help_text='Set when this notification relates to a chat message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chat.conversation')),
                ('property', models.ForeignKey(blank=True, help_text='Set when this notification relates to a property event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='properties.property')),
                ('user', models.ForeignKey(help_text='The user this notification is addressed to.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notification_user_read'), models.Index(fields=['type'], name='idx_notification_type'), models.Index(fields=['created_at'], name='idx_notification_created_at')],
            },
        ),
    ]
