# Generated by Django 6.0.4 on 2026-06-18 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, help_text='The verification decision taken by the admin.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Mandatory justification for rejections; optional notes for approvals.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='The admin/super_admin who performed this action.', on_delete=django.db.models.deletion.PROTECT, related_name='verification_logs', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(help_text='The property that was reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='properties.property')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'db_table': 'verification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property'], name='idx_verlog_property'), models.Index(fields=['admin'], name='idx_verlog_admin'), models.Index(fields=['action'], name='idx_verlog_action')],
            },
        ),
    ]
