# Generated by Django 6.0.4 on 2026-04-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
