# Generated by Django 6.0.4 on 2026-06-18 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('fraud', 'Fraud'), ('spam', 'Spam'), ('misleading', 'Misleading Information'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('reason', models.TextField(help_text='Detailed explanation from the reporter.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's official response or action note.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set when status transitions to RESOLVED.', null=True)),
                ('property', models.ForeignKey(help_text='The property being reported.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
                ('reporter', models.ForeignKey(help_text='The user who submitted this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_report_status'), models.Index(fields=['type'], name='idx_report_type'), models.Index(fields=['reporter'], name='idx_report_reporter'), models.Index(fields=['property'], name='idx_report_property')],
            },
        ),
    ]
